SHELL := /bin/bash
.DEFAULT_GOAL := help

ENV_FILE ?= .env

ifneq (,$(wildcard $(ENV_FILE)))
include $(ENV_FILE)
export $(shell sed -n 's/^\([A-Za-z_][A-Za-z0-9_]*\)=.*/\1/p' $(ENV_FILE))
endif

DOTNET_PROJECT := Backend/Api/Host/GenProxy.Api.Host.csproj
STACK_RUNNER_PROJECT := Backend/Tools/GenProxy.StackRunner/GenProxy.StackRunner.csproj
GEN_PROXY_LAUNCH_PROFILE ?= https
GEN_PROXY_BASE_URL ?= https://localhost:7001
PUBLIC_API_KEY ?= $(if $(ApiKeys__Keys__0),$(ApiKeys__Keys__0),dev-local-key)
LLAMA_RUNTIME_OWNER ?= rjxby
LLAMA_RUNTIME_REPO ?= llama-runtime
GENERATION_RUNTIME_PORT ?= 50051
SUMMARIZER_RUNTIME_PORT ?= 50052
RUNTIME_STARTUP_TIMEOUT ?= 60
RUNTIME_READY_STABILITY_SECONDS ?= 3
API_STARTUP_TIMEOUT ?= 60
SMOKE_RUNTIME_STARTUP_TIMEOUT ?= 180
SMOKE_MAIN_CONTEXT_SIZE ?= 768
SMOKE_SUMMARIZER_CONTEXT_SIZE ?= 4096
LLAMA_RUNTIME_DEFAULT_API_KEY ?= runtime-local-key
LLAMA_RUNTIME_EFFECTIVE_API_KEY := $(if $(LLAMA_RUNTIME_API_KEY),$(LLAMA_RUNTIME_API_KEY),$(LLAMA_RUNTIME_DEFAULT_API_KEY))
MAIN_WORKER_COUNT ?= 4
SUMMARIZER_WORKER_COUNT ?= 1
GEN_PROXY_RUNTIME_ADDRESSES := GenerationRuntime__Address=https://localhost:$(GENERATION_RUNTIME_PORT) PromptReducerRuntime__Enabled=true PromptReducerRuntime__Address=https://localhost:$(SUMMARIZER_RUNTIME_PORT)

.PHONY: help run stack-run demo smoke smoke-budget

help:
	@printf '%s\n' \
		'Available targets:' \
		'  make run        Run gen-proxy against already running runtimes' \
		'  make stack-run  Start local runtimes, run gen-proxy, clean up on exit' \
		'  make demo       Send a manual demo request to a running local gen-proxy stack' \
		'  make smoke      Start the local stack, run basic smoke checks, clean up' \
		'  make smoke-budget  Start a constrained local stack and run budget smoke checks'

run:
	@set -euo pipefail; \
	echo ">>> Starting gen-proxy against localhost runtimes"; \
	env \
		$(GEN_PROXY_RUNTIME_ADDRESSES) \
		GenerationRuntime__ApiKey="$(LLAMA_RUNTIME_EFFECTIVE_API_KEY)" \
		PromptReducerRuntime__ApiKey="$(LLAMA_RUNTIME_EFFECTIVE_API_KEY)" \
		dotnet run --launch-profile "$(GEN_PROXY_LAUNCH_PROFILE)" --project "$(DOTNET_PROJECT)"

stack-run:
	@env \
		ApiKeys__Keys__0="$(PUBLIC_API_KEY)" \
		LLAMA_RUNTIME_OWNER="$(LLAMA_RUNTIME_OWNER)" \
		LLAMA_RUNTIME_REPO="$(LLAMA_RUNTIME_REPO)" \
		LLAMA_RUNTIME_VERSION="$(LLAMA_RUNTIME_VERSION)" \
		GENERATION_RUNTIME_PORT="$(GENERATION_RUNTIME_PORT)" \
		SUMMARIZER_RUNTIME_PORT="$(SUMMARIZER_RUNTIME_PORT)" \
		RUNTIME_STARTUP_TIMEOUT="$(RUNTIME_STARTUP_TIMEOUT)" \
		RUNTIME_READY_STABILITY_SECONDS="$(RUNTIME_READY_STABILITY_SECONDS)" \
		API_STARTUP_TIMEOUT="$(API_STARTUP_TIMEOUT)" \
		LLAMA_RUNTIME_DEFAULT_API_KEY="$(LLAMA_RUNTIME_DEFAULT_API_KEY)" \
		LLAMA_RUNTIME_API_KEY="$(LLAMA_RUNTIME_API_KEY)" \
		MAIN_WORKER_COUNT="$(MAIN_WORKER_COUNT)" \
		SUMMARIZER_WORKER_COUNT="$(SUMMARIZER_WORKER_COUNT)" \
		MAIN_MODEL_PATH="$(MAIN_MODEL_PATH)" \
		MAIN_MODEL_ID="$(MAIN_MODEL_ID)" \
		SUMMARIZER_MODEL_PATH="$(SUMMARIZER_MODEL_PATH)" \
		SUMMARIZER_MODEL_ID="$(SUMMARIZER_MODEL_ID)" \
		MAIN_CONTEXT_SIZE="$(MAIN_CONTEXT_SIZE)" \
		SUMMARIZER_CONTEXT_SIZE="$(SUMMARIZER_CONTEXT_SIZE)" \
		dotnet run --project "$(STACK_RUNNER_PROJECT)" -- stack-run

demo:
ifeq ($(strip $(PROMPT)),)
	@env \
		GEN_PROXY_BASE_URL="$(GEN_PROXY_BASE_URL)" \
		GEN_PROXY_API_KEY="$(PUBLIC_API_KEY)" \
		MAIN_MODEL_ID="$(MAIN_MODEL_ID)" \
		./scripts/demo-request.sh
else
	@env \
		GEN_PROXY_BASE_URL="$(GEN_PROXY_BASE_URL)" \
		GEN_PROXY_API_KEY="$(PUBLIC_API_KEY)" \
		MAIN_MODEL_ID="$(MAIN_MODEL_ID)" \
		./scripts/demo-request.sh "$(PROMPT)"
endif

smoke:
	@env \
		GEN_PROXY_BASE_URL="$(GEN_PROXY_BASE_URL)" \
		ApiKeys__Keys__0="$(PUBLIC_API_KEY)" \
		LLAMA_RUNTIME_OWNER="$(LLAMA_RUNTIME_OWNER)" \
		LLAMA_RUNTIME_REPO="$(LLAMA_RUNTIME_REPO)" \
		LLAMA_RUNTIME_VERSION="$(LLAMA_RUNTIME_VERSION)" \
		GENERATION_RUNTIME_PORT="$(GENERATION_RUNTIME_PORT)" \
		SUMMARIZER_RUNTIME_PORT="$(SUMMARIZER_RUNTIME_PORT)" \
		RUNTIME_STARTUP_TIMEOUT="$(SMOKE_RUNTIME_STARTUP_TIMEOUT)" \
		RUNTIME_READY_STABILITY_SECONDS="$(RUNTIME_READY_STABILITY_SECONDS)" \
		API_STARTUP_TIMEOUT="$(SMOKE_RUNTIME_STARTUP_TIMEOUT)" \
		LLAMA_RUNTIME_DEFAULT_API_KEY="$(LLAMA_RUNTIME_DEFAULT_API_KEY)" \
		LLAMA_RUNTIME_API_KEY="$(LLAMA_RUNTIME_API_KEY)" \
		MAIN_WORKER_COUNT="$(MAIN_WORKER_COUNT)" \
		SUMMARIZER_WORKER_COUNT="$(SUMMARIZER_WORKER_COUNT)" \
		MAIN_MODEL_PATH="$(MAIN_MODEL_PATH)" \
		MAIN_MODEL_ID="$(MAIN_MODEL_ID)" \
		SUMMARIZER_MODEL_PATH="$(SUMMARIZER_MODEL_PATH)" \
		SUMMARIZER_MODEL_ID="$(SUMMARIZER_MODEL_ID)" \
		MAIN_CONTEXT_SIZE="$(MAIN_CONTEXT_SIZE)" \
		SMOKE_MAIN_CONTEXT_SIZE="$(SMOKE_MAIN_CONTEXT_SIZE)" \
		SUMMARIZER_CONTEXT_SIZE="$(SUMMARIZER_CONTEXT_SIZE)" \
		SMOKE_SUMMARIZER_CONTEXT_SIZE="$(SMOKE_SUMMARIZER_CONTEXT_SIZE)" \
		dotnet run --project "$(STACK_RUNNER_PROJECT)" -- smoke basic

smoke-budget:
	@env \
		GEN_PROXY_BASE_URL="$(GEN_PROXY_BASE_URL)" \
		ApiKeys__Keys__0="$(PUBLIC_API_KEY)" \
		LLAMA_RUNTIME_OWNER="$(LLAMA_RUNTIME_OWNER)" \
		LLAMA_RUNTIME_REPO="$(LLAMA_RUNTIME_REPO)" \
		LLAMA_RUNTIME_VERSION="$(LLAMA_RUNTIME_VERSION)" \
		GENERATION_RUNTIME_PORT="$(GENERATION_RUNTIME_PORT)" \
		SUMMARIZER_RUNTIME_PORT="$(SUMMARIZER_RUNTIME_PORT)" \
		RUNTIME_STARTUP_TIMEOUT="$(SMOKE_RUNTIME_STARTUP_TIMEOUT)" \
		RUNTIME_READY_STABILITY_SECONDS="$(RUNTIME_READY_STABILITY_SECONDS)" \
		API_STARTUP_TIMEOUT="$(SMOKE_RUNTIME_STARTUP_TIMEOUT)" \
		LLAMA_RUNTIME_DEFAULT_API_KEY="$(LLAMA_RUNTIME_DEFAULT_API_KEY)" \
		LLAMA_RUNTIME_API_KEY="$(LLAMA_RUNTIME_API_KEY)" \
		MAIN_WORKER_COUNT="$(MAIN_WORKER_COUNT)" \
		SUMMARIZER_WORKER_COUNT="$(SUMMARIZER_WORKER_COUNT)" \
		MAIN_MODEL_PATH="$(MAIN_MODEL_PATH)" \
		MAIN_MODEL_ID="$(MAIN_MODEL_ID)" \
		SUMMARIZER_MODEL_PATH="$(SUMMARIZER_MODEL_PATH)" \
		SUMMARIZER_MODEL_ID="$(SUMMARIZER_MODEL_ID)" \
		MAIN_CONTEXT_SIZE="$(MAIN_CONTEXT_SIZE)" \
		SMOKE_MAIN_CONTEXT_SIZE="$(SMOKE_MAIN_CONTEXT_SIZE)" \
		SUMMARIZER_CONTEXT_SIZE="$(SUMMARIZER_CONTEXT_SIZE)" \
		SMOKE_SUMMARIZER_CONTEXT_SIZE="$(SMOKE_SUMMARIZER_CONTEXT_SIZE)" \
		dotnet run --project "$(STACK_RUNNER_PROJECT)" -- smoke budget
