name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore Backend/GenProxy.sln

      - name: Build
        run: dotnet build Backend/GenProxy.sln -c Release --no-restore

      - name: Unit tests
        run: dotnet test Backend/Tests/GenProxy.Api.UnitTests/GenProxy.Api.UnitTests.csproj -c Release --no-build

      - name: Integration tests
        run: dotnet test Backend/Tests/GenProxy.Api.IntegrationTests/GenProxy.Api.IntegrationTests.csproj -c Release --no-build
